services:
  app:
    stdin_open: true
    tty: true
    image: container-fgzmmfy
    build:
      context: ./src
    ports:
      - "5001:5000"
    # volumes:
    #   - type: bind
    #     source: ./src/app
    #     target: /usr/src/app
    environment:
      ALLOWED_HOSTS: "127.0.0.1,localhost"